### ISSUE TITLE
USB connector and Capacitor through hole type

### ISSUE THREAD

**Issue by danko79** [JDet-74/AMIGA_PS2_Mouse#1]
Hi, I am interested in your project is the most complete have found on github, however i would like an all THT version both the USB port and the capacitor is it possible to make a mod?

**Comment by JDet-74** [comment]
> Hi, I am interested in your project is the most complete have found on github

Nice to hear ... THX

>  however i would like an all THT version both the USB port and the capacitor is it possible to make a mod?

What do you mean with "mod"? I can solder the SMD cap on the PCB, if you want to.

**Comment by danko79** [comment]
I meant if you could modify your project, putting this through hole
type capacitor and usb connector like in these pics.

https://leobot.net/productimages/506.jpeg

https://www.fxpstore.com/wp-content/uploads/2020/09/usb-a-type-female-straight-connector-500x500-1.jpg

Thanks Juri 

Il 14.10.2021 20:59 Kernelpanic ha scritto: 

>> Hi, I
am interested in your project is the most complete have found on
github
>> Nice to hear ... THX
> 
>> however i would like an all THT
version both the USB port and the capacitor is it possible to make a
mod?
>> What do you mean with "mod"? I can solder the SMD cap on the
PCB, if you want to.
> 
> --
> You are receiving this because you
authored the thread.
> Reply to this email directly, view it on GitHub
[1], or unsubscribe [2].
  


Con Tiscali Mobile Smart 70 hai 70 GB in 4G, minuti illimitati e 100 SMS a soli 7,99€ al mese http://tisca.li/Smart70

**Comment by JDet-74** [comment]
@danko79 
if you can not solder SMD components, I can solder the components, if you want.
I do not want to modify the PCB. I am too busy at the moment.
If you wanna do it, I can share the PCB project. 
I designed the PCB with JLCPSBs EasyEDA Designer.

**Comment by danko79** [comment]
ok, if you can share your project I'll see if I can edit it myself.

**Comment by JDet-74** [comment]
You have to be a registered user:
https://passport.easyeda.com/register?service=https%3A%2F%2Feasyeda.com%2Flogin

Project Homepage Link:
https://oshwlab.com/tdettling/amiga_ps2_mouse_copy

Open in Editor:
https://oshwlab.com/tdettling/amiga_ps2_mouse_copy
